name: modelshield
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults

dependencies:
  # Python版本
  - python=3.9

  # 核心深度学习框架 (从conda安装)
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - cudatoolkit=11.7

  # 科学计算库 (从conda安装)
  - numpy>=1.21.0
  - scipy>=1.7.0

  # 开发工具
  - fire=0.5.0
  - tqdm=4.65.0

  # pip安装的包 (conda不可用或版本不匹配)
  - pip
  - pip:
    # 模型和NLP库
    - transformers==4.28.1
    - datasets==2.10.1
    - huggingface_hub==0.13.1

    # 模型训练和微调
    - accelerate==0.17.1
    - bitsandbytes==0.37.1
    - deepspeed==0.9.0
    - peft>=0.3.0

    # API和工具
    - openai>=0.27.0

    # 界面
    - gradio