name: modelshield
channels:
  # 国内镜像源 - 清华大学镜像站
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/nvidia/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/huggingface/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  # 备用镜像源 - 中科大镜像站
  - https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  # 官方源作为备用
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python版本
  - python=3.9

  # 核心深度学习框架 (从conda安装)
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - cudatoolkit=11.7

  # 科学计算库 (从conda安装)
  - numpy>=1.21.0
  - scipy>=1.7.0

  # 开发工具
  - fire=0.5.0
  - tqdm=4.65.0

  # pip安装的包 (conda不可用或版本不匹配)
  - pip
  - pip:
    # 配置pip使用国内镜像源
    - --index-url https://pypi.tuna.tsinghua.edu.cn/simple/
    - --trusted-host pypi.tuna.tsinghua.edu.cn

    # 模型和NLP库
    - transformers==4.28.1
    - datasets==2.10.1
    - huggingface_hub==0.13.1

    # 模型训练和微调
    - accelerate==0.17.1
    - bitsandbytes==0.37.1
    - deepspeed==0.9.0
    - peft>=0.3.0

    # API和工具
    - openai>=0.27.0

    # 界面
    - gradio

# 环境变量配置 (可选)
variables:
  # 设置conda使用国内镜像源
  CONDA_CHANNEL_PRIORITY: flexible
  # 设置pip使用国内镜像源
  PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple/
  PIP_TRUSTED_HOST: pypi.tuna.tsinghua.edu.cn